// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2016.robot2018.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;

import org.usfirst.frc2016.robot2018.subsystems.*;

/**
 *
 */
public class AutoStraightGearBaseline extends CommandGroup {


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public AutoStraightGearBaseline() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
    	addSequential(new ResetGyro());
    	addSequential(new IsElevatorCalibrated());
        addSequential(new ShiftLow());
        addSequential(new ElevatorPrePickup());
        //addParallel(new ElevatorHigh());
      //  addSequential(new CompGrab());
      //  addSequential(new ArcadeDrive(speed, 0, 20));
       // addSequential(new CompGrab());
        //addSequential(new ArcadeDrive(-0.6, 0 , 78));
      //  addSequential(new DelaySeconds(2));
        //addSequential(new ArcadeDrive(-0.6, 0, 40));
        addSequential(new CameraDriveGyro());
        addSequential(new ElevatorHigh());

        addSequential(new DriveStraightForDistance(-.5, 28));
        addSequential(new GearRelease());
        addSequential(new DelaySeconds(1));
        addSequential(new ArcadeDrive(0.6, 0, 28));
        addSequential(new ArcadeDrive(0, 90, 0));
        addSequential(new ArcadeDrive(-0.8,90,88));
        addSequential(new ArcadeDrive(0, 0, 0));
        addSequential(new ArcadeDrive(-0.8, 0, 150));
        
    } 
}
