// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2016.robot2018.commands;
import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc2016.robot2018.Robot;

/**
 *
 */
public class AcquireCube extends Command {
	private int waitCounter;
	private final double DELAYPERCOUNT = .02;
	private final double TIME2WAIT = 1;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public AcquireCube() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.cubePickup);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	waitCounter = 0;
		//System.out.println("AcquireCube(): init " + waitCounter);
		Robot.cubePickup.autoEnd();
    	Robot.cubePickup.acquireCube();
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	waitCounter++;
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
		//System.out.println("AcquireCube(): isFinished " + waitCounter);
    	if (waitCounter >= (int)(TIME2WAIT/DELAYPERCOUNT)) {
    		return true;
    	}
        return false;
    }
		

    // Called once after isFinished returns true
    @Override
    protected void end() {
		//System.out.println("AcquireCube(): end" );
    	Robot.cubePickup.autoEnd();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    	Robot.cubePickup.autoEnd();
    }
}
